baseURL: https://blog.steinerkelvin.dev/
languageCode: en-us
title: Kelvin's Blog
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production  # to enable google analytics, opengraph, twitter-cards and schema.
    title: Kelvin's blog
    description: ""
    keywords: [blog]
    author: Kelvin Steiner 
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2006-01-02"
    defaultTheme: auto  # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    
    disqusShortname: "steinerkelvin-dev"

    math: false
    math_inline: true

    # assets:
    #     # disableHLJS: true # to disable highlight.js
    #     # disableFingerprinting: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    label:
        text: "blog.steinerkelvin.dev"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # # profile-mode
    # profileMode:
    #     enabled: false # needs to be explicitly set
    #     title: ExampleSite
    #     subtitle: "This is subtitle"
    #     imageUrl: "<img location>"
    #     imageWidth: 120
    #     imageHeight: 120
    #     imageTitle: my image
    #     buttons:
    #         - name: Posts
    #           url: posts
    #         - name: Tags
    #           url: tags

    # home-info mode
    homeInfoParams:
        Title: "Welcome ^-^"
        Content: Welcome to my blog

    socialIcons:
        - name: github
          url: "https://github.com/steinerkelvin"
        - name: twitter
          url: "https://twitter.com/steinerkelvin"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/1967121/steinerkelvin"

    analytics:
        google:
            SiteVerificationTag: "G-P1LVCZWNGN"
        # bing:
        #     SiteVerificationTag: "XYZabc"
        # yandex:
        #     SiteVerificationTag: "XYZabc"

    cover:
        hidden: true  # hide everywhere but not in structured data
        hiddenInList: true  # hide on list pages and home
        hiddenInSingle: true  # hide on single page

    editPost:
        URL: "https://github.com/steinerkelvin/steinerkelvin.github.io"
        Text: "Suggest Changes"  # edit text
        appendFilePath: true  # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - name: search
          url: /search/
          weight: 5
        - name: archive
          url: /archives/
          weight: 10
        - identifier: categories
          name: categories
          url: /categories/
          weight: 15
        - identifier: tags
          name: tags
          url: /tags/
          weight: 25
        # - identifier: example
        #   name: example.org
        #   url: https://example.org
        #   weight: 35
  
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
